{% set name = "ncephes" %}
{% set version = "1.0.15" %}
{% set sha256 = "c75b05cabe71ca3e2283178d9ddc5159bd2fb3993bbcbcabb1c840433454f380" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True           # [win and py<35]
  features:
    - vc14             # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - build_capi
    - cffi
    - pycparser
    - toolchain
    - vc 14           # [win]
  run:
    - python
    - cffi

test:
  requires:
    - pytest
    - numpy
    - numba
  imports:
    - ncephes
  commands:
    - python -c "import ncephes; ncephes.test()"

about:
  home: https://github.com/glimix/ncephes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface for the Cephes library'
  doc_url: http://ncephes.readthedocs.io
  dev_url: https://github.com/glimix/ncephes

extra:
  recipe-maintainers:
    - Horta
